site_name: Siddhi-IO-RabbitMQ
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi IO RabbitMQ: index.md
- API Docs:
  - 1.0.15: api/1.0.15.md
  - 1.0.14: api/1.0.14.md
  - latest: api/latest.md
- License: license.md
theme: material
